# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class G < Formula
  desc "Golang Version Manager"
  homepage "https://github.com/voidint/g"
  license "MIT"
  head "https://github.com/JS-mark/homebrew-g.git", branch: "main"
  version "1.5.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/voidint/g/releases/download/v1.5.0/g1.5.0.darwin-arm64.tar.gz"
      sha256 "14addde06095d5350c69ff37334308031c04b76fa72541352aeb64c79f4f70d7"

      def install
        bin.install "g" => "gmv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/voidint/g/releases/download/v1.5.0/g1.5.0.darwin-amd64.tar.gz"
      sha256 "f834b80ec1285d6d02fb512e48c731893cb0eade7be69d2ecb345816c2f66e29"

      def install
        bin.install "g" => "gmv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/voidint/g/releases/download/v1.5.0/g1.5.0.linux-amd64.tar.gz"
      sha256 "1c9f35a735c397909d5cfa16c06688531b9f645da68a450b8a12c98f3c65e94f"

      def install
        bin.install "g" => "gmv"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/voidint/g/releases/download/v1.5.0/g1.5.0.linux-arm.tar.gz"
      sha256 "85a60046c70f091ee5d220d8515368b9773ee178e7cd98528df375c377e10b54"

      def install
        bin.install "g" => "gmv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voidint/g/releases/download/v1.5.0/g1.5.0.linux-arm64.tar.gz"
      sha256 "9889ca23fe13684b26bfb83aec5af2e79a56966795999b7e89893e9ddf546d87"

      def install
        bin.install "g" => "gmv"
      end
    end
  end

  def caveats
    <<~EOS
      # 建议安装前清空`GOROOT`、`GOBIN`等环境变量
      $ curl -sSL https://raw.githubusercontent.com/voidint/g/master/install.sh | bash
      $ echo "unalias g" >> ~/.bashrc # 可选。若其他程序（如'git'）使用了'g'作为别名。
      $ source ~/.bashrc # 或者 source ~/.zshrc

      $ ~/.bashrc
      # export GOROOT="${HOME}/.g/go"
      # export PATH="${HOME}/.g/go/bin:$PATH"
      # export G_MIRROR=https://golang.google.cn/dl/
    EOS
  end

  test do
    system bin/"gmv", "ls-remote"
  end
end
