# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class G < Formula
  desc "Golang Version Manager"
  homepage "https://github.com/voidint/g"
  license "MIT"
  head "https://github.com/JS-mark/homebrew-g.git", branch: "main"
  version "1.5.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/voidint/g/releases/download/v1.5.2/g1.5.2.darwin-arm64.tar.gz"
      sha256 "3af235c47216e98380912befa2f4869110c66a6d22503e0cb69642c99a25648f"

      def install
        bin.install "g" => "gmv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/voidint/g/releases/download/v1.5.2/g1.5.2.darwin-amd64.tar.gz"
      sha256 "c2d07156617834ab2b8de03652a606ffd2d53b6936110a8c1b44321e37163752"

      def install
        bin.install "g" => "gmv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/voidint/g/releases/download/v1.5.2/g1.5.2.linux-amd64.tar.gz"
      sha256 "82101d57e367ef1db7cd0b12e82e334605aaebeabb72e1537dabb294d7a84ca6"

      def install
        bin.install "g" => "gmv"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/voidint/g/releases/download/v1.5.2/g1.5.2.linux-arm.tar.gz"
      sha256 "185e9169d8c15a4243e00772dcf3ae4a511a527590f3bc23892ebaeb0b756e01"

      def install
        bin.install "g" => "gmv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voidint/g/releases/download/v1.5.2/g1.5.2.linux-arm64.tar.gz"
      sha256 "832d88fb1f762c1b661dfa0b9bb5980af541d11cc410d118cfea4e471ccb043c"

      def install
        bin.install "g" => "gmv"
      end
    end
  end

  def caveats
    <<~EOS
      # 建议安装前清空`GOROOT`、`GOBIN`等环境变量
      $ curl -sSL https://raw.githubusercontent.com/voidint/g/master/install.sh | bash
      $ echo "unalias g" >> ~/.bashrc # 可选。若其他程序（如'git'）使用了'g'作为别名。
      $ source ~/.bashrc # 或者 source ~/.zshrc

      $ ~/.bashrc
      # export GOROOT="${HOME}/.g/go"
      # export PATH="${HOME}/.g/go/bin:$PATH"
      # export G_MIRROR=https://golang.google.cn/dl/
    EOS
  end

  test do
    system bin/"gmv", "ls-remote"
  end
end
