# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class G < Formula
  desc "Golang Version Manager"
  homepage "https://github.com/voidint/g"
  license "MIT"
  head "https://github.com/JS-mark/homebrew-g.git", branch: "main"
  version "1.6.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/voidint/g/releases/download/v1.6.0/g1.6.0.darwin-arm64.tar.gz"
      sha256 "a2f2e01806da9fe98da4726a24833f69ab0986347b21688bf3018820f764ca54"

      def install
        bin.install "g" => "gmv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/voidint/g/releases/download/v1.6.0/g1.6.0.darwin-amd64.tar.gz"
      sha256 "a7b8f666807947a95362eb63b44c797e8077cede0ece77496c66deee2b58d40a"

      def install
        bin.install "g" => "gmv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/voidint/g/releases/download/v1.6.0/g1.6.0.linux-amd64.tar.gz"
      sha256 "135390891f0e50b20d5cdc8b378f10c5da0cc08d2a1fb9f63f334b6c3707f7f2"

      def install
        bin.install "g" => "gmv"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/voidint/g/releases/download/v1.6.0/g1.6.0.linux-arm.tar.gz"
      sha256 "4949c3a9af43e0eae3f1ba5fa4ce91d520229a572dd0d409dc84365f124c7968"

      def install
        bin.install "g" => "gmv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/voidint/g/releases/download/v1.6.0/g1.6.0.linux-arm64.tar.gz"
      sha256 "95c466d68db0b3916718e71f64910761876841b0c4f508b56d613ccfd2bc89c1"

      def install
        bin.install "g" => "gmv"
      end
    end
  end

  def caveats
    <<~EOS
      # 建议安装前清空`GOROOT`、`GOBIN`等环境变量
      $ curl -sSL https://raw.githubusercontent.com/voidint/g/master/install.sh | bash
      $ echo "unalias g" >> ~/.bashrc # 可选。若其他程序（如'git'）使用了'g'作为别名。
      $ source ~/.bashrc # 或者 source ~/.zshrc

      $ ~/.bashrc
      # export GOROOT="${HOME}/.g/go"
      # export PATH="${HOME}/.g/go/bin:$PATH"
      # export G_MIRROR=https://golang.google.cn/dl/
    EOS
  end

  test do
    system bin/"gmv", "ls-remote"
  end
end
